package FormularioPacheco;

import Conexion_SQL.ConexionPacheco;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;

public class Celularbp extends javax.swing.JFrame {

    ConexionPacheco cc = new ConexionPacheco();
    Connection con =cc.conexion();
   
    public Celularbp() {
        initComponents();
        setTitle("REGISTRO DE CELULAR");
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TCliente = new javax.swing.JTextField();
        TMarca = new javax.swing.JTextField();
        TRam = new javax.swing.JTextField();
        TMemoria = new javax.swing.JTextField();
        BNuevo = new javax.swing.JButton();
        BGuardar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPersona = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 94, 87));

        jLabel1.setText("DNI:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Ram:");

        jLabel4.setText("Memoria:");

        BNuevo.setText("Nuevo");
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        BActualizar.setText("Actualizar");
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TMemoria))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TRam, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(BGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(BEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(BActualizar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNuevo)
                    .addComponent(BGuardar)
                    .addComponent(BEliminar)
                    .addComponent(BActualizar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel5.setText("Busqueda:");

        TBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBuscarActionPerformed(evt);
            }
        });
        TBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBuscarKeyReleased(evt);
            }
        });

        TPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TPersona);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        InsertDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        eliminarRegistro();
        mostrarDatos();
        limpiarCajas();
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        actualizarDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_BActualizarActionPerformed

    private void TBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBuscarActionPerformed

    private void TBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBuscarKeyReleased
        filtrarDatos(TBuscar.getText());
    }//GEN-LAST:event_TBuscarKeyReleased

    private void TPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPersonaMouseClicked
        int FileSelect=TPersona.rowAtPoint(evt.getPoint());
        TCliente.setText(TPersona.getValueAt(FileSelect, 1).toString());
        TMarca.setText(TPersona.getValueAt(FileSelect, 2).toString());
        TRam.setText(TPersona.getValueAt(FileSelect, 3).toString());
        TMemoria.setText(TPersona.getValueAt(FileSelect, 4).toString()); 
    }//GEN-LAST:event_TPersonaMouseClicked
                                      

    public void mostrarDatos(){
        String[] titulos={"ID", "DNI","Marca", "Ram", "Memoria"};
        String[] registros=new String[6];
        DefaultTableModel modelo=new DefaultTableModel(null,titulos);
        
        String SQL="select * from celular";
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);  
            while(rs.next()){
            registros[0]=rs.getString("idcelular");
            registros[1]=rs.getString("dni");
            registros[2]=rs.getString("marca");
            registros[3]=rs.getString("ram");
            registros[4]=rs.getString("memoria");
            modelo.addRow(registros);
            }
            TPersona.setModel(modelo);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR AL MOSTRAR DATOS" + e.getMessage());
        }
    }
    
    public void InsertDatos(){
        try{
            String SQL="insert into celular(dni,marca,ram,memoria) values (?,?,?,?)";
            PreparedStatement pst= con.prepareStatement(SQL);
            
            pst.setString(1,TCliente.getText());
            pst.setString(2,TMarca.getText());
            
            pst.setDouble(3,Double.parseDouble(TRam.getText()));
            
            pst.setDouble(4,Double.parseDouble(TMemoria.getText()));
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, "Error de Conexion" + e.getMessage());
            
        }
    }
    
    public void filtrarDatos(String valor){
    String[] titulos={"ID", "DNI", "Marca", "Ram", "Memoria"};
    String[] registros=new String[6];
    DefaultTableModel modelo=new DefaultTableModel(null,titulos);
        
        String SQL="select * from celular where dni like '%"+valor+"%'";
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);  
            while(rs.next()){
            registros[0]=rs.getString("idcelular");
            registros[1]=rs.getString("dni");
            registros[2]=rs.getString("marca");
            registros[3]=rs.getString("ram");
            registros[4]=rs.getString("memoria");
            modelo.addRow(registros);
            }
            TPersona.setModel(modelo);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR AL MOSTRAR DATOS" + e.getMessage());
        }
    }
    
    public void eliminarRegistro(){
        int filaSeleccionada=TPersona.getSelectedRow();
        try{
            String SQL="delete from celular where idcelular="+TPersona.getValueAt(filaSeleccionada,0);
            Statement st=con.createStatement();
            int n=st.executeUpdate(SQL);
            if(n>=0){
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al Eliminar Registro"+ e.getMessage());
        }
    }
    
    public void actualizarDatos(){
        try{
            String SQL="update celular set dni=?,marca=?,ram=?,memoria=? WHERE idcelular=?" ;
            int filaSeleccionado=TPersona.getSelectedRow();
            String dao =(String)TPersona.getValueAt(filaSeleccionado,0);
            
            PreparedStatement pst= con.prepareStatement(SQL);
            
            pst.setString(1,TCliente.getText());
            pst.setString(2,TMarca.getText());
            
            pst.setDouble(3,Double.parseDouble(TRam.getText()));
            
            pst.setDouble(4,Double.parseDouble(TMemoria.getText()));
           
            pst.setString(5,dao);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, "Error de Edicion" + e.getMessage());
        }
    }
    
     public void limpiarCajas(){
        TCliente.setText("");
        TMarca.setText("");
        TRam.setText("");
        TMemoria.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Celularbp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Celularbp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Celularbp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Celularbp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Celularbp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JTextField TBuscar;
    private javax.swing.JTextField TCliente;
    private javax.swing.JTextField TMarca;
    private javax.swing.JTextField TMemoria;
    private javax.swing.JTable TPersona;
    private javax.swing.JTextField TRam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
